name: Rust-APP-Test-Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Install dependencies
      run: sudo apt-get install -y jq bc

    - name: Run tests and generate coverage report
      run: |
        cargo llvm-cov clean --workspace
        cargo llvm-cov --json --output-path=coverage.json

    - name: Check coverage
      id: coverage-check
      run: |
        COVERAGE=$(jq '.data[0].totals.lines.pct' < coverage.json)
        echo "Coverage is $COVERAGE%"
        if (( $(echo "$COVERAGE < 50" | bc -l) )); then
          echo "Code coverage is below 50%"
          exit 1
        fi